language: python

matrix:
  include:
    - python: 3.4
      dist: precise
      env: TOXENV=py34 DIST=precise SUDO=required
      sudo: required

    - python: pypy3
      dist: trusty
      env: TOXENV=pypy3 DIST=trusty SUDO=required
      sudo: required

    - python: 3.3
      dist: precise
      env: TOXENV=py33 DIST=precise SUDO=false
      sudo: false

    - python: 2.7
      dist: precise
      env: TOXENV=py27 DIST=precise SUDO=false
      sudo: false

    - python: 2.6
      dist: precise
      env: TOXENV=py26 DIST=precise SUDO=false
      sudo: false

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then pip install 'virtualenv<14' ; fi
    - travis_retry pip install tox

script:
    - id
    - env
    - python --version
    - tox
    - ls -l /usr/bin/sudo
    - NO_SUDO=`test -u /usr/bin/sudo || echo $?`
    - echo $NO_SUDO
    - python -c "import platform; print(platform.linux_distribution());"
    - python -c "import platform; print(platform.uname())"
    - python -c "import os, stat; print(os.lstat('/usr/bin/sudo')[0] & stat.S_ISUID)"
