env:
  global:
    URL=https://www.proofwiki.org/wiki/Main_Page

matrix:
  include:
    # OK
    - env: DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    # OK
    - env: DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 2.7

    # Python 3.3 and 2.x before 2.7.9 do not have ssl.PROTOCOL_TLSv1_2
    - env: DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.3

    # A http URL that redirects to https causes urllib3.PoolManager to raise MaxRetryError
    # https://github.com/shazow/urllib3/issues/869
    - env: URL=http://www.proofwiki.org/wiki/Main_Page DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    # These all fail on precise containers
    - env: DIST=precise SUDO=false TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1 TEST_CURL_EXPLICIT=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    # OK; SUDO=required uses a later image of precise
    - env: DIST=precise SUDO=required TEST_PYTHON=1 TEST_PYTHON_EXPLICIT=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: required
      language: python
      python: 3.4

    # These fail on precise with sudo, as the command line options dont exist
    - env: DIST=precise SUDO=required TEST_WGET_EXPLICIT=1 TEST_CURL_EXPLICIT=1
      os: linux
      dist: precise
      sudo: required
      language: python
      python: 3.4

    # OK; trusty mostly works, except wget as shown in the next job
    - env: DIST=trusty SUDO=required TEST_PYTHON=1 TEST_PYTHON_EXPLICIT=1 TEST_CURL=1 TEST_CURL_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    # Trusty wget fails
    - env: DIST=trusty SUDO=required TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    # Installing debian sid's libssl1.0.2 (via openssl) doesnt help
    - env: DIST=trusty SUDO=required APT=debian-sid-openssl TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    # Installing debian sid's wget doesnt help
    - env: DIST=trusty SUDO=required APT=debian-sid-wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl+wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
            - wget
      language: python
      python: 3.4

    # Installing debian sid's wget ...
    - env: DIST=trusty SUDO=required APT=debian-sid-wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

    # Doing an upgrade doesnt help
    - env: DIST=trusty SUDO=required APT=everything TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    # Doing an upgrade and installing debian wget doesnt help
    - env: DIST=trusty SUDO=required APT=everything-debian-sid-wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    # Building from source fails
    - env: DIST=trusty SUDO=required BUILD=wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything BUILD=wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    # Doing an upgrade using debian sid fails during upgrade
    - env: DIST=trusty SUDO=required APT=debian-sid-everything
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
      language: python
      python: 3.4

    # Building from source using debian sid's openssl fails
    - env: DIST=trusty SUDO=required APT=debian-sid-openssl BUILD=wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
            - libgnutls-dev
      language: python
      python: 3.4

    # Using debian sid's openssl doesnt help
    - env: DIST=precise SUDO=false APT=debian-sid-openssl TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    # Using debian sid's libgnutls fails during installation
    - env: DIST=precise SUDO=false APT=debian-sid-libgnutls26
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - libgnutls26
      language: python
      python: 3.4

    # Using debian sid's libgnutls fails during installation
    - env: DIST=precise SUDO=false APT=debian-sid-libgnutlsxx27
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - libgnutlsxx27
      language: python
      python: 3.4

    # Using debian sid's libgnutls fails during installation
    - env: DIST=precise SUDO=false APT=debian-sid-libgnutls-openssl27
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - libgnutls-openssl27
      language: python
      python: 3.4

    # Using debian sid's wget fails during installation
    - env: DIST=precise SUDO=false APT=debian-sid-wget
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

  allow_failures:
    - env: DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.3

    - env: URL=http://www.proofwiki.org/wiki/Main_Page DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1 TEST_CURL_EXPLICIT=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    - env: DIST=precise SUDO=required TEST_WGET_EXPLICIT=1 TEST_CURL_EXPLICIT=1
      os: linux
      dist: precise
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl+wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
            - wget
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything-debian-sid-wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required BUILD=wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything BUILD=wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-everything
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl BUILD=wget TEST_WGET=1 TEST_WGET_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
            - libgnutls-dev
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false APT=debian-sid-openssl TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false APT=debian-sid-wget
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

install:
    - if [[ "$APT" == "everything-debian-sid-wget" || "$APT" == "everything" || "$APT" == "debian-sid-everything" ]]; then
        sudo apt-get -qq update ;
        sudo apt-get -yf -o Dpkg::Options::="--force-confold" upgrade ;
      fi
    - if [[ "$APT" == "everything-debian-sid-wget" ]]; then
        curl -sSL "https://ftp-master.debian.org/keys/archive-key-7.0.asc" | sudo -E apt-key add - ;
        echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null ;
        sudo apt-get -qq update ;
        sudo apt-get -yf install wget ;
      fi
    - if [[ "$BUILD" == "wget" ]]; then
        wget http://ftp.gnu.org/gnu/wget/wget-1.17.tar.xz ;
        tar -xJf wget-1.17.tar.xz ;
        cd wget-1.17 ;
        ./configure ;
        sudo make install ;
        cd .. ;
      fi
    - if [[ "$TEST_PYTHON" == 1 || "$TEST_PYTHON_EXPLICIT" == 1 ]]; then
        pip install "urllib3[secure]" "requests[security]" ;
      fi

before_script:
    - env
    - python --version
    - wget --version
    - curl --version
    - curl --help

script:
    - if [[ "$TEST_PYTHON" == 1 ]]; then
        python -c "import requests; print(requests.get('$URL').status_code);" ;
      fi
    - if [[ "$TEST_PYTHON_EXPLICIT" == 1 ]]; then
        python -c "import ssl, urllib3; r = urllib3.PoolManager(ssl_version=ssl.PROTOCOL_TLSv1_2, retries=10).connection_from_url('$URL').request('GET', '$URL', assert_same_host=False); print(r.status);" ;
      fi
    - if [[ "$TEST_WGET" == 1 ]]; then
        wget $URL ;
      fi
    - if [[ "$TEST_WGET_EXPLICIT" == 1 ]]; then
        wget --secure-protocol=TLSv1_2 $URL ;
      fi
    - if [[ "$TEST_CURL" == 1 ]]; then
        curl -v $URL ;
      fi
    - if [[ "$TEST_CURL_EXPLICIT" == 1 ]]; then
        curl -v --tlsv1.2 $URL ;
      fi
