language: python

python:
- 3.5

env:
  global:
    - PYENV_ROOT=$HOME/.pyenv

  matrix:
    - PYENV_VERSION=pypy-5.0.1
    - PYENV_VERSION=2.6.6  # no 2.6.5
    - PYENV_VERSION=2.7.2
    - PYENV_VERSION=3.4.0
    - PYENV_VERSION=jython-2.7.1b3

script:
  - git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
  - $PYENV_ROOT/bin/pyenv install --skip-existing "$PYENV_VERSION"
  - virtualenv --python="$PYENV_ROOT/versions/$PYENV_VERSION/bin/python" "$HOME/virtualenvs/$PYENV_VERSION"
  - source "$HOME/virtualenvs/$PYENV_VERSION/bin/activate"
  - python --version

cache:
  directories:
    - $PYENV_ROOT
