language: ruby
sudo: required

matrix:
  include:
    - dist: precise
      env: MYDIST=precise
    - dist: trusty
      env: MYDIST=trusty

before_install:
  - printenv
  - ./download.sh
  - ./install.sh
