language: python

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
- pypy3

script:
  - python -c "import py; print(py.__version__);"
  # pytest==2.7.0 requires py>=1.4.25
  # pytest-xdist==1.15 requires py>=1.4.22
  # Installing py==1.4.22 will cause a PluginValidationError
  # Lets see if py==1.4.25 works
  - echo 'py==1.4.25' > requirements.txt
  - echo 'pytest-xdist==1.15' >> requirements.txt
  - echo 'pytest==2.7.0' >> requirements.txt
  - pip install -r requirements.txt
  - echo '' > test.py
  - py.test test.py
