matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - python-ipaddr
            - python-openssl
            - python-requests
            - python-urllib3
            - python-six
            - python-certifi
            - python-cryptography
            - python-ndg-httpsclient
            - libssl1.0.2
            - python-cffi
            - python-enum34
            - python-idna
            - python-ipaddress
            - python-pyasn1

before_install:
    - id
    - env
    - python --version
    - if [[ "$VIRTUAL_ENV" == '' ]]; then
        export INSTALL_USER_FLAG=--user ;
      else
        export INSTALL_USER_FLAG= ;
      fi

script:
    - python -c "import requests; requests.get('https://www.wikipedia.org/')"
    - python -c "import requests; requests.get('https://testssl-expire-r2i2.disig.sk/index.en.html')"
