language: python

python:
- 2.7

env:
  global:
    - PYENV_ROOT=$HOME/.pyenv

  matrix:
    - PYENV_VERSION=pypy-2.4.0
    - PYENV_VERSION=pypy-2.5.0
    - PYENV_VERSION=pypy-2.5.1
    - PYENV_VERSION=pypy-2.6.0
    - PYENV_VERSION=pypy-2.6.1
    - PYENV_VERSION=pypy-4.0.1
    - PYENV_VERSION=pypy-5.0.0
    - PYENV_VERSION=pypy-5.0.1
    - PYENV_VERSION=pypy-5.1
    - PYENV_VERSION=pypy-5.1.1

before_install:
  - git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
  - $PYENV_ROOT/bin/pyenv install --skip-existing "$PYENV_VERSION"
  - virtualenv --python="$PYENV_ROOT/versions/$PYENV_VERSION/bin/python" "$HOME/virtualenvs/$PYENV_VERSION"
  - source "$HOME/virtualenvs/$PYENV_VERSION/bin/activate"
  - python --version

script:
  - python -c "import sys; print(sys.stdout.encoding)"
  - python pwb.py version
  - PYTHONIOENCODING=UTF-8 python pwb.py version
  - PYTHONIOENCODING=UTF8 python pwb.py version
