matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      addons:
        apt:
          packages:
            - python-requests
            - python-openssl

    - language: generic
      addons:
        apt:
          packages:
            - python-pip
            - python-setuptools
            - python-requests
            - python-openssl

before_install:
    - id
    - env
    - python --version
    - if [[ "$VIRTUAL_ENV" == '' ]]; then
        export INSTALL_USER_FLAG=--user ;
      else
        export INSTALL_USER_FLAG= ;
      fi

script:
    - python setup.py test || true
    - pip install --upgrade $INSTALL_USER_FLAG setuptools
    - python setup.py test || true
    - python setup.py install $INSTALL_USER_FLAG
    - python setup.py test
    - python -c "import requests; requests.get('https://www.wikipedia.org/')"
