language: python

before_install:
    - id
    - env
    - ls -al ~/bin || true
    - python --version
    - if [[ "$VIRTUAL_ENV" == '' ]]; then
        export PIP_USER_FLAG=--user ;
      else
        export PIP_USER_FLAG= ;
      fi

install:
    - travis_retry pip install $PIP_USER_FLAG tox 'virtualenv<14'

script:
    - tox
