matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
            - kubuntu-backports
            - mopidy-stable
            - google-chrome
            - google-cloud
            - git-core
          packages:
            - python-ipaddr
            - python-openssl=0.13-2ubuntu6
            - python-requests
            - python-six
            - python-certifi
            - python-ndg-httpsclient
            - libssl1.0.2
            - python-cffi
            - python-enum34
            - python-idna
            - python-ipaddress
            - python-pyasn1
            - ca-certificates

before_install:
    - id
    - env
    - python --version
    - if [[ "$VIRTUAL_ENV" == '' ]]; then
        export INSTALL_USER_FLAG=--user ;
      else
        export INSTALL_USER_FLAG= ;
      fi
    - #apt-cache policy python-cryptography
    - #apt-cache policy python-openssl
    - #sudo echo "deb http://ftp.us.debian.org/debian stable main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null
    - #sudo echo "deb http://ftp.us.debian.org/debian testing main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null
    - #sudo -E apt-get -yq update &>> ~/apt-get-update.log
    - apt-cache policy python-cryptography
    - apt-cache policy python-openssl

script:
    - pip install --upgrade cryptography
    - pip install --upgrade PyOpenSSL
    - python -W always test_requests.py
    # python -W always test_requests.py
    # diff -u /usr/lib/python2.7/dist-packages/requests/__init__.py requests__init__.py || true
    # sudo cp requests__init__.py /usr/lib/python2.7/dist-packages/requests/__init__.py
    # python -W always test_requests.py
