matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      addons:
        apt:
          packages:
            - python-ipaddr
            - python-requests
            - python-openssl

before_install:
    - id
    - env
    - python --version

script:
    - python setup.py install
    - python setup.py test
