language: python

matrix:
  include:
    - python: 3.4
      dist: precise
      env: TOXENV=py34
      sudo: required

    - python: pypy3
      dist: trusty
      env: TOXENV=pypy3
      sudo: false

    - python: 3.3
      dist: precise
      env: TOXENV=py33
      sudo: false

install:
    - travis_retry pip install tox

script:
    - env
    - python --version
    - tox
    - ls -l /usr/bin/sudo
    - SUDO_ENABLED=`test -u /usr/bin/sudo || echo $?`
    - echo $SUDO_ENABLED
    - pip install requests
    - python -c "import requests; print(requests.get('http://www.proofwiki.org/wiki/$1').status_code);"
    - wget --help
    - wget "http://www.proofwiki.org/wiki/$1"
