language: python

matrix:
  include:
    - python: 3.4
      dist: precise
      env: TOXENV=py34 DIST=precise SUDO=required
      sudo: required

    - python: pypy3
      dist: trusty
      env: TOXENV=pypy3 DIST=trusty SUDO=required
      sudo: required

    - python: 3.3
      dist: precise
      env: TOXENV=py33 DIST=precise SUDO=false
      sudo: false

    - python: 2.7
      dist: precise
      env: TOXENV=py27 DIST=precise SUDO=false
      sudo: false

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then pip install 'virtualenv<14' ; fi
    - travis_retry pip install tox

script:
    - env
    - python --version
    - tox
    - ls -l /usr/bin/sudo
    - SUDO_ENABLED=`test -u /usr/bin/sudo || echo $?`
    - echo $SUDO_ENABLED
    - if [[ "$SUDO_ENABLED" == 1 ]]; then
        sudo apt-get -qq update ;
        sudo apt-get upgrade ;
      fi
    - pip install requests
    - python -c "import requests; print(requests.get('http://www.proofwiki.org/wiki/$1').status_code);"
    - wget --help
    - wget "http://www.proofwiki.org/wiki/$1"
