matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      addons:
        apt:
          packages:
            - python-ipaddr
            - python-requests
            - python-openssl

before_install:
    - id
    - env
    - python --version
    - cat $HOME/.pydistutils.cfg || true
    - export PYTHONPATH=~/.py-site-packages
    - echo '[install]' > $HOME/.pydistutils.cfg
    - echo 'install_lib = ~/.py-site-packages' > $HOME/.pydistutils.cfg
    - echo 'install_scripts = ~/bin' > $HOME/.pydistutils.cfg
    - mkdir ~/.py-site-packages

script:
    - python setup.py test
