language: python

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
- pypy3

script:
  - python -c "import py; print(py.__version__);"
  - echo 'pytest-xdist' > requirements.txt
  - echo 'pytest>3' >> requirements.txt
  - pip install -r requirements.txt
  - echo '' > test.py
  - py.test test.py
