language: node_js
node_js: 6
install:
  - git clone --depth 1 https://github.com/wooorm/remark
  - cd remark
  - npm install lerna
  - npm install --production
  - npm install remark-validate-links
  - cd ..
script:
  - node remark/packages/remark-cli/cli.js --version
  - node remark/packages/remark-cli/cli.js --frail --no-stdout -u remark-validate-links test.md
  - node remark/packages/remark-cli/cli.js test.md
  - rm -rf remark
  - echo '----- Now released remark -------'
  - travis_retry npm install -g remark-cli remark-validate-links
  - remark --version
  - remark --frail --no-stdout -u remark-validate-links test.md
  - remark test.md
