matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'

before_install:
    - id
    - env
    - python --version
    - cat $HOME/.pydistutils.cfg || true

script:
    - python setup.py test || true
    - python setup.py install
    - python setup.py test
