language: generic

addons:
  apt:
    packages:
      - python-virtualenv

env:
  global:
    - PYENV_ROOT=$HOME/.pyenv

matrix:
  include:
    - env: PYENV_VERSION=jython-2.7.0 DIST=precise
      dist: precise
    - env: PYENV_VERSION=jython-dev DIST=precise
      dist: precise
    - env: PYENV_VERSION=miniconda2-4.0.5 DIST=precise
      dist: precise
    - env: PYENV_VERSION=miniconda3-4.0.5 DIST=precise
      python: 3.5
      dist: precise
    - env: PYENV_VERSION=stackless-3.4.1 DIST=precise
      dist: precise
    - env: PYENV_VERSION=stackless-dev DIST=precise
      dist: precise
    - env: PYENV_VERSION=ironpython-2.7.5 DIST=precise
      dist: precise
    - env: PYENV_VERSION=ironpython-dev DIST=precise
      dist: precise

    - env: PYENV_VERSION=pypy-2.4.0 DIST=precise
      dist: precise
    - env: PYENV_VERSION=pypy-2.6.1 DIST=precise
      dist: precise
    - env: PYENV_VERSION=pypy-4.0.1 DIST=precise
      dist: precise
    - env: PYENV_VERSION=pypy-5.0.1 DIST=precise
      dist: precise
    - env: PYENV_VERSION=pypy-5.1 DIST=precise
      dist: precise
    - env: PYENV_VERSION=pypy-5.1.1 DIST=precise
      dist: precise

    - env: PYENV_VERSION=pypy-2.4.0 DIST=trusty
      dist: trusty
      sudo: required
    - env: PYENV_VERSION=pypy-2.6.1 DIST=trusty
      dist: trusty
      sudo: required
    - env: PYENV_VERSION=pypy-4.0.1 DIST=trusty
      dist: trusty
      sudo: required
    - env: PYENV_VERSION=pypy-5.0.1 DIST=trusty
      dist: trusty
      sudo: required
    - env: PYENV_VERSION=pypy-5.1 DIST=trusty
      dist: trusty
      sudo: required
    - env: PYENV_VERSION=pypy-5.1.1 DIST=trusty
      dist: trusty
      sudo: required

before_script:
  # Travis trusty has a basically empty directory at $PYENV_ROOT
  - (test -d "$PYENV_ROOT" && find "$PYENV_ROOT") || true
  - which pyenv || true

script:
  - test '!' -d "$PYENV_ROOT" || rm -rf "$PYENV_ROOT"

  - git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
  - $PYENV_ROOT/bin/pyenv install --skip-existing "$PYENV_VERSION"
  - virtualenv --python="$PYENV_ROOT/versions/$PYENV_VERSION/bin/python" "$HOME/virtualenvs/$PYENV_VERSION"
  - source "$HOME/virtualenvs/$PYENV_VERSION/bin/activate"
  - python --version
