language: python

before_install:
    - id
    - env
    - ls -al ~/bin || true
    - python --version
    - if [[ "$VIRTUAL_ENV" == '' ]]; then
        export PIP_USER_FLAG=--user ;
      else
        export PIP_USER_FLAG= ;
      fi

install:
    - if [[ "$TRAVIS_PYTHON_VERSION" == "3.2" ]]; then pip install 'virtualenv<14' ; fi
    - travis_retry pip install $PIP_USER_FLAG tox

script:
    - tox
