language: python

matrix:
  include:
    - python: 3.4
      dist: precise
      env: DIST=precise SUDO=required
      sudo: required

    - python: 3.4
      dist: trusty
      env: DIST=trusty SUDO=required APT=debian-sid-openssl
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl

    - python: 3.4
      dist: precise
      env: DIST=precise SUDO=false
      sudo: false

    - python: 3.4
      dist: precise
      env: DIST=precise SUDO=false APT=debian-sid-openssl
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl

script:
    - env
    - python --version
    - pip install "requests[security]"
    - python -c "import requests; print(requests.get('http://www.proofwiki.org/wiki/$1').status_code);"
    - wget --version
    - wget "http://www.proofwiki.org/wiki/$1"
