language: node_js
node_js:
  - node
  - iojs
  - 7
  - 6
  - 5
  - 4

before_script:
  - npm install

script:
  - cd /tmp
  - echo foo > foo.md
  - PATH=$PATH:TRAVIS_BUILD_DIR/node_modules/.bin remark --use 'lint="maximumLineLength": 2' foo.md
