language: python

matrix:
  include:
    - python: 3.4
      dist: precise
      env: TOXENV=py34
      sudo: required

    - python: pypy3
      dist: trusty
      env: TOXENV=pypy3
      sudo: false

install:
    - travis_retry pip install tox

script:
    - env
    - tox
    - ls -l /usr/bin/sudo
