matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      addons:
        apt:
          packages:
            - python-ipaddr
            - python-requests
            - python-pyopenssl

before_install:
    - id
    - env
    - python --version
    - cat $HOME/.pydistutils.cfg || true

script:
    - python setup.py test
