env:
  global:
    URL=https://proofwiki.org/wiki/Main_Page

matrix:
  include:
    - env: DIST=precise SUDO=false TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=precise SUDO=required TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl TEST_PYTHON=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-wget TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false APT=debian-sid-openssl TEST_PYTHON=1
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false APT=debian-sid-wget TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

before_script:
    - env
    - python --version
    - wget --version

script:
    - if [[ "$TEST_PYTHON" == 1 ]]; then
        pip install "requests[security]" ;
        python -c "import requests; print(requests.get('$URL').status_code);" ;
      fi
    - if [[ "$TEST_WGET" == 1 ]]; then
        wget $URL ;
      fi
    - if [[ "$TEST_CURL" == 1 ]]; then
        curl -v $URL ;
      fi
