language: python

matrix:
  include:
    - os: osx
      language: generic
      python: 2.7

script:
  - python --version
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PYTHON_VERSION
  - pip --version
  - pip install --user tox
  - export PATH=$PATH:$HOME/bin
  - tox --version
