env:
  global:
    URL=https://proofwiki.org/wiki/Main_Page

matrix:
  include:
    - env: DIST=precise SUDO=false TEST_PYTHON_EXPLICIT=1 TEST_CURL_EXPLICIT=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: false
      language: python
      python: 3.4

    - env: DIST=precise SUDO=required TEST_PYTHON=1 TEST_PYTHON_EXPLICIT=1 TEST_WGET=1 TEST_CURL=1 TEST_CURL_EXPLICIT=1
      os: linux
      dist: precise
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required TEST_PYTHON=1 TEST_PYTHON_EXPLICIT=1 TEST_CURL=1 TEST_CURL_EXPLICIT=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-wget TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-openssl+wget TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
            - wget
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything-debian-sid-wget TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required BUILD=wget TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=everything BUILD=wget TEST_WGET=1
      os: linux
      dist: trusty
      sudo: required
      language: python
      python: 3.4

    - env: DIST=trusty SUDO=required APT=debian-sid-everything
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          sources:
            - debian-sid
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false APT=debian-sid-openssl TEST_PYTHON=1 TEST_WGET=1 TEST_CURL=1
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - openssl
      language: python
      python: 3.4

    - env: DIST=precise SUDO=false APT=debian-sid-wget
      os: linux
      dist: precise
      sudo: false
      addons:
        apt:
          sources:
            - debian-sid
          packages:
            - wget
      language: python
      python: 3.4

before_script:
    - env
    - python --version
    - wget --version

install:
    - if [[ "$APT" == "everything-debian-sid-wget" || "$APT" == "everything" || "$APT" == "debian-sid-everything" ]]; then
        sudo apt-get -qq update ;
        sudo apt-get -yf -o Dpkg::Options::="--force-confold" upgrade ;
      fi
    - if [[ "$APT" == "everything-debian-sid-wget" ]]; then
        curl -sSL "https://ftp-master.debian.org/keys/archive-key-7.0.asc" | sudo -E apt-key add - ;
        echo "deb http://ftp.us.debian.org/debian unstable main contrib non-free" | sudo tee -a /etc/apt/sources.list > /dev/null ;
        sudo apt-get -qq update ;
        sudo apt-get -yf install wget ;
      fi
    - if [[ "$BUILD" == "wget" ]]; then
        wget http://ftp.gnu.org/gnu/wget/wget-1.17.tar.xz ;
        tar -xJf wget-1.17.tar.xz ;
        cd wget-1.17 ;
        ./configure ;
        sudo make install ;
        cd .. ;
      fi
    - if [[ "$TEST_PYTHON" == 1 || "$TEST_PYTHON_EXPLICIT" == 1 ]]; then
        pip install "urllib3[secure]" "requests[security]" ;
      fi

script:
    - if [[ "$TEST_PYTHON" == 1 ]]; then
        python -c "import requests; print(requests.get('$URL').status_code);" ;
      fi
    - if [[ "$TEST_PYTHON_EXPLICIT" == 1 ]]; then
        python -c "import ssl, urllib3; conn = urllib3.connection_from_url('$URL', ssl_version=ssl.PROTOCOL_TLSv1_2); r = conn.request('GET', '$URL'); print(r.status);" ;
      fi
    - if [[ "$TEST_WGET" == 1 ]]; then
        wget $URL ;
      fi
    - if [[ "$TEST_CURL" == 1 ]]; then
        curl -v $URL ;
      fi
    - if [[ "$TEST_CURL_EXPLICIT" == 1 ]]; then
        curl -v --tlsv1.2 $URL ;
      fi
