matrix:
  include:
    - language: python
      python: '2.7_with_system_site_packages'
      addons:
        apt:
          packages:
            - python-requests
            - python-openssl

    - language: generic
      addons:
        apt:
          packages:
            - python-pip
            - python-setuptools
            - python-requests
            - python-openssl

before_install:
    - id
    - env
    - python --version

script:
    - python setup.py test || true
    - pip install --upgrade --user setuptools
    - python setup.py test || true
    - python setup.py install --user
    - python setup.py test
