language: python

python:
- 2.6
- 2.7
- 3.2
- 3.3
- 3.4
- 3.5
- pypy
- pypy3

script:
  - python -c "import multiprocessing; print(multiprocessing.cpu_count());"
  - pip install psutil
  - python -c "import psutil; print(psutil.cpu_count(True), psutil.cpu_count(False));"
  - python -c "import os; print(os.cpu_count());"
