language: python

matrix:
  include:
    - os: osx
      language: bash
      python: 2.7

install:
  - brew install python3

script:
  - sed 's/pip-log.txt/*.txt/' .gitignore > .gitignore.new
  - diff -u .gitignore .gitignore.new
  - python --version
  - echo $TRAVIS_OS_NAME
  - echo $TRAVIS_PYTHON_VERSION
  - pip --version
  - pip install --user tox
  - export PATH=$PATH:~/Library/Python/2.7/bin/
  - tox --version
  - python3 --version
  - python3 -m ensurepip
  - python3 -m pip install tox
