init:
  - "SET PATH=%PATH%;c:\\Python27\\Scripts;C:\\cygwin\bin"
  - "ECHO PATH=%PATH%"

install:
  - cmd: python -m pip install -r requirements.txt

build: off

test_script:
  - cmd: bash.exe -x fetch.sh

